### ISSUE TITLE
ScreenOrientation Cordova Plugin not working anymore on IOS 16 (Simulator/Real)

### ISSUE THREAD

**Issue by fernandaj222** [apache/cordova-plugin-screen-orientation#108]
# Bug Report
Hi! I'm working with the screen orientation plugin (v. 3.0.2) for an Ionic app with Angular. Still, once I tried it on an ios device with the latest version (16) the plugin stopped working, I tested it on Android and older versions of iOS and it still works. 

**Note.** I have already created a ticket with support but I would like to know when they estimate to have an official solution for this problem, I have also tried the solutions in this PR but they have not worked.

## Problem
ScreenOrientation Cordova Plugin not working anymore on IOS 16
## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by fernandaj222** [comment]
this PR is https://github.com/apache/cordova-plugin-screen-orientation/pull/107

**Comment by zerefel** [comment]
I've been banging my head with this problem and it seems to affect one of the most basic functionalities of a mobile app. Can we have an update on when it's expected to be solved and merged?

**Comment by VasanthCBH** [comment]
Any update on when we are merging the PR to fix this issue

**Comment by breautek** [comment]
> Any update on when we are merging the PR to fix this issue

Looks like we are currently awaiting for the PR author to make some requested changes.

**Comment by ThodorisElissaios** [comment]
Any update?

**Comment by breautek** [comment]
This issue should be resolved by https://github.com/apache/cordova-plugin-screen-orientation/pull/107

It can be tested by installing the dev version via git:

```
cordova plugin remove cordova-plugin-screen-orientation
cordova plugin add https://github.com/apache/cordova-plugin-screen-orientation.git
```
