### ISSUE TITLE
Latest release 4 years ago

### ISSUE THREAD

**Issue by jindrichkuba** [apache/cordova-plugin-screen-orientation#111]
[3.0.2](https://www.npmjs.com/package/cordova-plugin-screen-orientation/v/3.0.2)

Hi, can I help you somehow? What is blocking new release? Latest release was 4 years ago, thanks

**Comment by TiBz0u** [comment]
@jindrichkuba 
See 3.0.3 milestones
https://github.com/apache/cordova-plugin-screen-orientation/milestone/1

**Comment by hoi4** [comment]
There are currently no open tickets in the milestone. Would be awesome to have the fixes (especially the fix for iOS16) released 🙏🏻

**Comment by TiBz0u** [comment]
> There are currently no open tickets in the milestone. Would be awesome to have the fixes (especially the fix for iOS16) released 🙏🏻

There was 2 at my reply time. Two tickets were fixed 3 days ago ; so it's coming :)

**Comment by NiklasMerz** [comment]
I started the release process. Stay updated for a release in the near future: https://lists.apache.org/thread/p0pg0kqfqrowc158ncq3shcow7zmcxj2

**Comment by sujeet-matchps** [comment]
@NiklasMerz  Can you release the beta version?

**Comment by NiklasMerz** [comment]
Apache Cordova does not release beta versions. I will work on the release later this week when I have time. Please be patient for a little more. Thank you very much.

**Comment by sujeet-matchps** [comment]
> Apache Cordova does not release beta versions. I will work on the release later this week when I have time. Please be patient for a little more. Thank you very much.

Thank you for your quick reply and humble support on this @NiklasMerz, I 100% agree. 

This week we have a production release.

Kindly do the needful support.

Thank you...

**Comment by NiklasMerz** [comment]
The release is out: https://cordova.apache.org/news/2023/02/24/screen-orientation-plugin-3.0.3.html
