### ISSUE TITLE
landscape-primary/landscape-secondary orientation is wrong in iOs 16.4

### ISSUE THREAD

**Issue by dmitry-platogo** [apache/cordova-plugin-screen-orientation#117]
# Bug Report

## Problem
Native support of ScreenOrienation was introduced in [Safari 16.4](https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes):
> Added support for ScreenOrientation.type, ScreenOrientation.angle, and ScreenOrientation.onchange.

So the native (browser) support for `window.screen.orientation.type` was added, but added incorrectly.

In Cordova's implementation it is done according to [W3 spec](https://w3c.github.io/screen-orientation/#the-current-screen-orientation-type-and-angle):
> For screens with a natural portrait orientation:
portrait-primary: 0°
landscape-primary: 90°
portrait-secondary: 180°
landscape-secondary: 270°

But for Safari 16.4 when `window.orientation` value is `90`, then `screen.orientation.type` value is `landscape-secondary` (and when `-90` (i.e. 270) then `landscape-primary`). So `landscape-primary` and `landscape-secondary` are mixed up.

Although it looks like a Safari bug, I can no longer rely on `window.screen.orientation.type` value shipped by `cordova-plugin-screen-orientation` plugin, I had to switch to `window.orientation` in my code. 

Maybe the incorrect Safari behaviour could be fixed inside the plugin, so the value of `window.screen.orientation.type` would stay consistent in any iOs version?

**Comment by xuxueyong** [comment]
> 

How do I make modifications on the plugin side? Could you please guide me? Thank you.

**Comment by virkrishna786** [comment]
Any Solution for this I am also facing same issue

**Comment by dmitry-platogo** [comment]
> Any Solution for this I am also facing same issue

In my code for iOs I switched from checking `screen.orientation.type` to `window.orientation`, because `window.orientation` value is solid for all iOs versions (although `window.orientation` is deprecated by web standards)

**Comment by breautek** [comment]
This issue should be resolved by https://github.com/apache/cordova-plugin-screen-orientation/pull/116

which forces the implementation to use the cordova implementation which works according to spec.

I don't think this change has seen a public release yet, but you can give it a test by installing the dev version via the master branch.
