### ISSUE TITLE
lock on iOS does not work right after device ready event 

### ISSUE THREAD

**Issue by chiefego** [apache/cordova-plugin-screen-orientation#34]
When calling screen.lock immediately after device ready event fires in iOS, the screen is not getting forced. However, it works when calling it after 4000ms.

**Comment by janpio** [comment]
What does "is not getting forced" mean?

**Comment by chiefego** [comment]
Sorry, what I mean is that when the phone's orientation is `portrait` and you call `screen.lock('landscape')` right after `onDeviceReady` the phone orientation is not changed. If you manually rotate the phone then it locks it. However, when making the same call with a 4s timeout the phone will rotate to landscape automatically.

**Comment by sagrawal31** [comment]
This is happening with me randomly as well on iPhoneX and some time in iPhone 6

**Comment by sagrawal31** [comment]
I actually see some new commits after the release of 3.0.1 which fixes some landscape orientation issues. Is 3.0.2-dev branch production ready?

**Comment by janpio** [comment]
You tell us ;) Usually there should only be working code in `master`.

**Comment by am** [comment]
@janpio This is still happening on 3.0.1

**Comment by mpotter-modus** [comment]
Confirmed - we're having the same issue. Looks like this was fixed in a89e94c

Any plans to publish an update to the NPM repo @jcesarmobile / @macdonst ?

**Comment by jcesarmobile** [comment]
Closing as it's fixed in that commit

**Comment by mpotter-modus** [comment]
@jcesarmobile could we get a new release please so the changes can be pulled from the NPM repo?

**Comment by jcesarmobile** [comment]
I don't know how to do Apache plugin releases, sorry, it's not as simple as publishing it in npm
