### ISSUE TITLE
cordova-plugin-screen-orientation does not work

### ISSUE THREAD

**Issue by r4-2017** [apache/cordova-plugin-screen-orientation#37]
I need help from someone! I try use the plugin above with code: `function fixpositionscreen(){
try{
alert('trying...');
if (screen.orientation.lock('portrait-primary')) { alert('yes, it was blocked');}
else {alert('no, it was not blocked....');}
}
catch(err){
alert(err);
}
}
fixpositionscreen();

So, I receive message saying: "yes, it was blocked' but the screen is not locked. I can still turn the device to either side. The screen continues to reposition. Help me.
PS: SO is Android
Android Version 5.1
Cordova/Phonegap version 8.0
Using phonegap serve command for provider server of application for the device

**Comment by janpio** [comment]
> Cordova/Phonegap version 8.0

Cordova and Phonegap are different things nowadays. If you have a problem using the Phonegap CLI, you will have to debug this with the Phonegap people.

> Using phonegap serve command for provider server of application for the device

What does that mean?

Can you recreate the problem just using Cordova in a new app started with `cordova create`?

**Comment by janpio** [comment]
That unfortunately doesn't help. Please try to recreate using Cordova CLI. If you have the error then, put the project on Github so we can take a look.

**Comment by breautek** [comment]
Closing as stale
