### ISSUE TITLE
Production Build not created after ionic-native screen-orientation plugin is installed

### ISSUE THREAD

**Issue by ghulamakbar14** [apache/cordova-plugin-screen-orientation#46]
# Bug Report

## Problem
Production Build not created after ionic-native screen-orientation plugin is installed

### What is expected to happen?
Production Build should be created after ionic-native screen-orientation plugin is installed. Without production flag build is created but I want to create it with production flag.

### What does actually happen?
Production build is not created. I get the following error:

> Unable to load PlatformApi from platform. Error: Cannot find module 'properties-parser'
Unhandled error. (The platform "android" does not appear to be a valid cordova platform. It is missing API.js. android not supported.

### Command or Code:

`ionic cordova build android --prod --aot --vendor-chunk --common-chunk --delete-output-path --buildOptimizer`

### Environment, Platform, Device
Android

### Version information

- Ionic: 4.12.0
- Cordova: 9.0.0
- ionic-native/screen-orientation: ^5.5.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
You created this issue in the repository of the underlying Cordova plugin, not Ionic Native or Ionic CLI. There are no production builds with Cordova CLI or this plugin, so this doesn't seem related.
