### ISSUE TITLE
Ios issue( lock not working)

### ISSUE THREAD

**Issue by arun8888s** [apache/cordova-plugin-screen-orientation#69]
# Bug Report

### What is expected to happen?

iOS app and iPad should lock into landscape mode.

### What does actually happen?
 Only iOS app is locked in landscape mode and not the iPad

## Information
Tested using iPad Air with iOS version 12.4.6

We are using Cordova version 8.1.2 and 
Plugin version- Cordova-plugin-screen-Orientation 3.0.2

## Checklist

- [ x] I searched for existing GitHub issues

**Comment by timbru31** [comment]
Have you seen https://github.com/apache/cordova-plugin-screen-orientation/issues/59?

**Comment by govindpn** [comment]
When the orientation is locked to landscape, the app screen orientation is locked perfectly, but the status bar rotates when the iPad screen orientation changes. 

`<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
	</array>`

**Comment by arun8888s** [comment]
@timbru31  , Is this issue will be resolved by the new enhancement you have mentioned in the
https://github.com/apache/cordova-plugin-screen-orientation/issues/59 ?

**Comment by arun8888s** [comment]
@timbru31 ,any update on this issue?

**Comment by govind-n** [comment]
@timbru31 Could you please comment. I didn't get any fix for the issue that I have posted earlier.
