### ISSUE TITLE
Screen lock NotSupportedError  for orientation 'landscape', 'portrait'

### ISSUE THREAD

**Issue by mkranz** [apache/cordova-plugin-screen-orientation#70]
# Bug Report

## Problem

`screen.orientation.lock` promise is always rejected with the error `NotSupportedError`

### What is expected to happen?

Promise should be resolved successfully and screenlock occurs

### What does actually happen?

Promise is rejected with NotSupportedError

## Information

The version prior to the merging of https://github.com/apache/cordova-plugin-screen-orientation/pull/66 worked as expected.

It appears this [line ](https://github.com/apache/cordova-plugin-screen-orientation/blob/3c08d393ffe0df5fa16f7fcbab06c22648dcc3ed/www/screenorientation.js#L87) was inadvertently changed such that it never checks if the orientation is supported, but will always fail instead.

Removing the quotes from 'orientation' should fix this issue

### Environment, Platform, Device

Tested on iOS 13.5.1  iPad Air 2 

### Version information

Master

## Checklist

- [x ] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by rushsteve1** [comment]
I am also experiencing this on an iPad running iOS 13.6 and an Android tablet running Android 7.
